add Installation/Retro_i486
AOSC-Dev/wiki pull request #10
Opened 2021-02-13 10:07 UTC by Si-Huan

2021-02-13 11:00 UTC, Si-Huan commented on content/aosc-os/installation/retro_i486.md
> +Check the resulting `/etc/fstab file`, and edit it in case of errors.
这儿 `/etc/fstab file` 应该是 `/etc/fstab` file

2021-02-17 03:50 UTC, MingcongBai requested changes

2021-02-17 03:50 UTC, MingcongBai commented on content/aosc-os/installation/retro_i486.md
> +It is impossible to install AOSC OS/Retro without a working Live environment or an installed copy of Linux distribution on your local storage. Live disc images are not yet available for AOSC OS/Retro
"Live images."

2021-02-18 20:00 UTC, MingcongBai requested changes

2021-02-18 20:00 UTC, MingcongBai commented on content/aosc-os/installation/retro_i486.md
> +Check the resulting `/etc/fstab file`, and edit it in case of errors.
`/etc/fstab` file *.

2021-02-18 20:00 UTC, MingcongBai approved these changes

2021-02-18 20:00 UTC, merged