developer: update packaging/advanced-techniques.zh.md
AOSC-Dev/wiki pull request #60
Opened 2023-12-10 01:11 UTC by Suyun114

2023-12-10 01:21 UTC, cthbleachbit commented on content/developer/packaging/advanced-techniques.zh.md
> +  - `self`：当存在 autobuild 或构建文件时，使用用户创建的 autobuild 或构建文件作为构建脚本。
构建文件 -> build

2023-12-10 01:21 UTC, cthbleachbit commented on content/developer/packaging/advanced-techniques.zh.md
> +  - `dummy`：生成一个空包，这在生成元包是很有用。
原来的翻译比较好，或者说“通常只用于生成元包”

2023-12-10 01:21 UTC, cthbleachbit commented on content/developer/packaging/advanced-techniques.zh.md
> +请注意，我们使用了一个简单的函数来将日志信息打印到构建日志中，这个函数被称为 `abinfo()`。`abinfo()` 的工作方式类似于 `echo` 程序。只需要在脚本中调用 `abinfo "Desired build information"`，这段信息就会被记录到构建日志中。使用 `abinfo()` 作为注释构建脚本的方式被认为是一种良好的实践，因为这对于可能对于后来的维护者来说可能
上面的没删

2023-12-10 01:21 UTC, cthbleachbit commented on content/developer/packaging/advanced-techniques.zh.md
> +有时 Autobuild3 可以很好地处理构建过程，但最终产出的包可能需要一些额外的调整（例如：man 页面的目录不对，需要将 shell 完成脚本复制到 `$PKGDIR` 等）。在这种情况下，我们使用 `autobuild/beyond` 脚本。与 `autobuild/build` 类似，这个脚本作为纯 Bash 脚本在构建过程之后执行。
原文没删

2023-12-10 01:21 UTC, cthbleachbit commented on content/developer/packaging/advanced-techniques.zh.md
> +这是一个来自 `TREE/extra-web/aria2` 的例子。这里我们需要安装 `aria2c` 的 bash<sub>completion</sub> 文件，所以我们使用如下的 `autobuild/beyond` 脚本。
这里为什么会有 sub……一次性改成“bash 命令行补全支持”

2023-12-10 02:01 UTC, MingcongBai requested changes

2023-12-10 02:01 UTC, MingcongBai commented on content/developer/packaging/advanced-techniques.zh.md
> +请注意，我们使用了一个简单的函数来将日志信息输出到构建日志中，这个函数被称为 `abinfo()`。`abinfo()` 的工作方式类似于 `echo` 程序。只需要在脚本中调用 `abinfo "Desired build information"`，这段信息就会被记录到构建日志中。使用 `abinfo()` 对构建脚本进行注释是一种良好的实践，因为这有助于后来的维护者。还有一个类似的函数是
> 请注意，我们使用了一个简单的函数来将日志信息输出到构建日志中，这个函数被称为……

此处的“一个”其实不需要；此外“这个函数被称为”读起来有点拗口，我建议这么写：

“请注意，上述例子中的 `abinfo()` 用于在构建日志中输出状态信息，其工作方式类似于 `echo`”

全文其余部分有许多“一个”实际上读起来都有点不地道，同“它”一样，尽可能少用

> 使用 `abinfo()` 对构建脚本进行注释是一种良好的实践，因为这有助于后来的维护者。

读起来有点像英文，可以用“好习惯一类的词汇代替，未必需要和原句式一致

2023-12-10 02:01 UTC, MingcongBai commented on content/developer/packaging/advanced-techniques.zh.md
> +但有时，源代码可能具有不同的条带级别，例如，这个补丁的条带级别为 3：
“条带级别”这个翻译明显不对

2023-12-10 02:01 UTC, MingcongBai commented on content/developer/packaging/advanced-techniques.zh.md
> +Autobuild3 提供了测试功能。
此处的“了”不必要

2023-12-10 02:17 UTC, cthbleachbit commented on content/developer/packaging/advanced-techniques.zh.md
> +  - `self`：当存在 autobuild 或 build 文件时，使用用户创建的 autobuild 或 build 文件作为构建脚本。
Oh 我意识到这里说的是路径，就应该是 `autobuild/build`，翻译的时候拿 backtick 包一下

2024-02-21 04:18 UTC, MingcongBai approved these changes

2024-02-21 04:18 UTC, merged