aoscc/2024-guide: correct airport bus info, expand bus section, wording
AOSC-Dev/wiki pull request #64
Opened 2024-06-09 17:16 UTC by TechCiel

2024-06-10 17:13 UTC, billchenchina requested changes

2024-06-10 17:13 UTC, billchenchina commented on content/community/aoscc/2024-guide.zh.md
> +- 吉大南校（东门）站（距**东门** 100m）：可乘坐 **G13** 路、**G222** 路、**Z315** 路，均距始发站两站
站名不存在？但是好像和上面的重名了？

2024-06-10 17:13 UTC, billchenchina commented on content/community/aoscc/2024-guide.zh.md
> +乘坐 1/3/4 号线可到达**长春站**，2/6 号线可到达**长春西站**。其中 3 号线两侧分别可到达**伪满皇宫**、**净月潭**国家森林公园。
```suggestion
乘坐 1/3/4 号线可到达**长春站**，2/6 号线可到达**长春西站**。其中 3 号线起终点分别可到达**伪满皇宫**、**净月潭**国家森林公园。
```

2024-06-10 17:13 UTC, billchenchina commented on content/community/aoscc/2024-guide.zh.md
> +乘坐 1/3/4 号线可到达**长春站**，2/6 号线可到达**长春西站**。其中 3 号线两侧分别可到达**伪满皇宫**、**净月潭**国家森林公园。
3 号线终点是长影世纪城吧

2024-06-10 18:06 UTC, TechCiel commented on content/community/aoscc/2024-guide.zh.md
> +- 吉大南校（东门）站（距**东门** 100m）：可乘坐 **G13** 路、**G222** 路、**Z315** 路，均距始发站两站
我明天去现场看看到底叫什么站。

2024-06-12 21:27 UTC, TechCiel commented on content/community/aoscc/2024-guide.zh.md
> +- 吉大南校（东门）站（距**东门** 100m）：可乘坐 **G13** 路、**G222** 路、**Z315** 路，均距始发站两站
fixed

2024-06-13 01:53 UTC, billchenchina approved these changes
lgtm, thank you!

2024-06-13 02:58 UTC, MingcongBai approved these changes
Incorporated review from @KexyBiscuit to clarify that attendees may also grab their swags at the venue.

2024-06-13 02:59 UTC, MingcongBai commented
Very nice guide!

2024-06-13 02:59 UTC, merged