fix Raspberry Pi installation documentation:Fix raspberry os documentation.
AOSC-Dev/wiki pull request #74
Opened 2024-12-22 08:44 UTC by model-err

鉴于树莓派的BSP即将合并进入主源,因此修改了树莓派的相关文档.
并修改了一个拼写错误.

2024-12-22 13:32 UTC, Cyanoxygen requested changes
Great work! However there're some extra work to be done.

2024-12-22 13:32 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.md
> +- Hardware Decoding is not working on ARM64 architecture,see [here](https://github.com/raspberrypi/userland/blob/9f3f9054a692e53b60fca54221a402414e030335/CMakeLists.txt#L11) and [here](https://www.ra
```suggestion
- Hardware decoding is not working on 64-bit systems, see [here](https://github.com/raspberrypi/userland/blob/9f3f9054a692e53b60fca54221a402414e030335/CMakeLists.txt#L11) and [here](https://www.raspberrypi.org/forums/viewtopic.php?t=232684&start=25) for details.
```

2024-12-22 13:32 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/troubleshooting.md
> +## Kernel paniced
```suggestion
## Kernel panicked
```

Both of us are wrong. It is actually pani _ck_ ed.

2024-12-22 13:32 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/troubleshooting.zh.md
> +## 内核崩溃了 (paniced)
Ditto.

2024-12-22 13:32 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.zh.md
> +- ARM64上的视频硬解码不工作.参见[这里](https://github.com/raspberrypi/userland/blob/9f3f9054a692e53b60fca54221a402414e030335/CMakeLists.txt#L11)与[这里](https://www.raspberrypi.org/forums/viewtopic.php?t=232684&start
1. 需使用中文标点。
2. 需要在英文、半角数字与中文之间加入空格，如：
```diff
- ARM64上的视频解码不工作
+ ARM64 上的视频解码不工作
```
3. 此句翻译较为生硬，建议改为：
“64 位系统没有硬件视频解码支持”

2024-12-22 13:32 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.zh.md
> +- 目前树莓派的单板支持包(BSP)仍未合并至主源,等待bugfix后合并ing...
```suggestion

```

可以删掉这一行了。

2024-12-22 13:32 UTC, Cyanoxygen commented on content/aosc-os/installation/manual/arm-raspberry-pi.zh.md
> +description = "在树莓派上安装AOSC OS"
```suggestion
title = "在树莓派上安装 AOSC OS"
description = "在树莓派上安装 AOSC OS"
```

2024-12-22 13:32 UTC, Cyanoxygen commented on content/aosc-os/installation/manual/arm-raspberry-pi.zh.md
> +请参考[这里](https://wiki.aosc.io/aosc-os/devices/raspberrypi/4b/installation/)。
应该详细告知。建议改为：
“现有[新的文章](https://wiki.aosc.io/aosc-os/devices/raspberrypi/4b/installation/)可供参考，本文已不再提供。”

2024-12-22 13:32 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.zh.md
> +可以直接执行
与上文不连贯。建议改成：

```
为了让树莓派运行安装的 AOSC OS，要在安装过程中安装一系列单板支持包，例如内核及引导用固件。您可以执行如下命令安装所需要的支持包：
```

2024-12-22 14:36 UTC, model-err commented on content/aosc-os/devices/raspberrypi/4b/installation.zh.md
> +可以直接执行
应该在[这个commit](https://github.com/AOSC-Dev/wiki/pull/74/commits/b9d4c1d3f1117a42d1d09def12fced98e558ea61)里修了？

2024-12-22 14:39 UTC, model-err commented on content/aosc-os/devices/raspberrypi/4b/troubleshooting.md
> +## Kernel paniced
但是我能查到的文章里的内核恐慌都是“kernel panic”...

2024-12-23 14:05 UTC, model-err commented on content/aosc-os/devices/raspberrypi/4b/installation.md
> +- Hardware Decoding is not working on ARM64 architecture,see [here](https://github.com/raspberrypi/userland/blob/9f3f9054a692e53b60fca54221a402414e030335/CMakeLists.txt#L11) and [here](https://www.ra
fixed.

2024-12-23 14:05 UTC, model-err commented on content/aosc-os/devices/raspberrypi/4b/installation.zh.md
> +- ARM64上的视频硬解码不工作.参见[这里](https://github.com/raspberrypi/userland/blob/9f3f9054a692e53b60fca54221a402414e030335/CMakeLists.txt#L11)与[这里](https://www.raspberrypi.org/forums/viewtopic.php?t=232684&start
现在应该改过来了……

2025-01-09 13:12 UTC, model-err commented
So...could it be merged now?Or are there more things needing to be fixed?

2025-01-09 13:14 UTC, MingcongBai commented
> So...could it be merged now?Or are there more things needing to be fixed?

I'm deferring this to @Cyanoxygen as he is currently working on the toolchain.

2025-01-09 13:33 UTC, Cyanoxygen requested changes

2025-01-09 13:33 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.md
> +- Some BCM2837 based Raspberry Pi 2 boards (2B Rev1.2,maybe slow)
```suggestion

```

Let's just remove Pi 2 from the supported list.

2025-01-09 13:33 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.md
> +- Hardware decoding is not working on 64-bit systems,see [here](https://github.com/raspberrypi/userland/blob/9f3f9054a692e53b60fca54221a402414e030335/CMakeLists.txt#L11) and [here](https://www.raspbe
```suggestion
- Hardware decoding is not working on 64-bit systems, see [here](https://github.com/raspberrypi/userland/blob/9f3f9054a692e53b60fca54221a402414e030335/CMakeLists.txt#L11) and [here](https://www.raspberrypi.org/forums/viewtopic.php?t=232684&start=25)
```

You are missing a space after the punctuation.

2025-01-09 13:33 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.md
> +- The raspi-config tool provided in the aosc package list was come from [cyanberry-config](https://github.com/AOSC-Archive/cyanberry-config),but now it is archived,and not suggested to use.
```suggestion
- The `raspi-config` tool previously available in the AOSC package repository came from [cyanberry-config](https://github.com/AOSC-Archive/cyanberry-config). This project is now archived and no longer recommended to use.
```

Ditto. (Don't forget to modify the Chinese version accordingly.)

2025-01-09 13:33 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.zh.md
> +- AOSC主源中提供的raspi-config工具来自[cyanberry-config](https://github.com/AOSC-Archive/cyanberry-config),但是目前已归档,不再建议使用
```suggestion
- AOSC 主源中提供的 `raspi-config` 工具来自 [cyanberry-config](https://github.com/AOSC-Archive/cyanberry-config)，但是目前已归档，不再建议使用。
```

1. 注意使用中文标点。
2. 注意在中文与英文、半角符号间添加空格。

2025-01-09 13:33 UTC, Cyanoxygen commented on content/aosc-os/installation/manual/arm-raspberry-pi.md
You may restore this file and replace the content with the same notice below.

2025-01-09 13:33 UTC, Cyanoxygen commented on content/aosc-os/devices/raspberrypi/4b/installation.md
>  ```
```suggestion
The BSP packages are now present in the main suite, so you don't have to add `bsp-rpi` suite to your `sources.list`. Simply run the following command to install the BSP packages:

```sh
apt update
apt install linux+kernel+rpi64+lts
```

I think rewriting the section like that would be better.

2025-01-09 14:13 UTC, model-err commented
now they should be fixed...

2025-02-02 14:24 UTC, closed without merging